# Generated by Django 5.2 on 2025-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('order_count', models.IntegerField(default=0, verbose_name='Количество заказов')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая выручка')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'ordering': ['-date'],
            },
        ),
    ]
