# Generated by Django 5.1.7 on 2025-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
